# Generated by Django 3.2 on 2021-04-08 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='squirrel_info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Longtitude', models.FloatField(help_text='Squirrel longtitude', max_length=50)),
                ('Latitude', models.FloatField(help_text='Squirrel latitude', max_length=50)),
                ('Unique_Squirrel_ID', models.CharField(help_text='The unique ID of the squirrel', max_length=50)),
                ('Hectare', models.CharField(help_text='Hector grid ID', max_length=50)),
                ('Shift', models.CharField(choices=[('AM', 'AM'), ('PM', 'PM')], help_text='Whether the sighting session occurred in the morning or afternoon', max_length=50)),
                ('Date', models.DateField(help_text='Sighting session date')),
                ('Hectare_squirrel_number', models.IntegerField(help_text='Number within the chronological sequence of squirrel sightings for a discrete sighting session')),
                ('Age', models.CharField(choices=[('adult', 'Adult'), ('juvenile', 'Juvenile')], help_text='Age, either Adult or Juvenile', max_length=50)),
                ('Primary_fur_color', models.CharField(choices=[('gray', 'Gray'), ('cinnamon', 'Cinnamon'), ('black', 'Black')], help_text='The primary fur color of the squirrels', max_length=50)),
                ('Highlight_fur_color', models.CharField(help_text='The highlight fur color of the squirrels', max_length=50)),
                ('combination_color', models.CharField(help_text='permutations of primary and highlight colors observed', max_length=50)),
                ('Color_notes', models.CharField(help_text='commentary on the squirrel ', max_length=50)),
                ('Location', models.CharField(choices=[('above ground', 'Above Ground'), ('ground plane', 'Ground Plane')], help_text='location of the squirrel, either Ground Plane or Above Ground ', max_length=50)),
                ('Specific_location', models.CharField(help_text='specific location of the squirrel ', max_length=50)),
                ('Running', models.BooleanField(help_text='If the squirrel is seen running')),
                ('Chasing', models.BooleanField(help_text='If the squirrel is seen chasing')),
                ('Climbing', models.BooleanField(help_text='If the squirrel is seen climbing')),
                ('Eating', models.BooleanField(help_text='If the squirrel is seen eating')),
                ('Foraging', models.BooleanField(help_text='If the squirrel is seen foraging')),
                ('Kuks', models.BooleanField(help_text='If the squirrel is heard kukking')),
                ('Quaas', models.BooleanField(help_text='If the squirrel is heard quaaing')),
                ('Moans', models.BooleanField(help_text='If the squirrel is heard moaning')),
                ('Tail_flags', models.BooleanField(help_text='If the squirrel is seen flagging its tail')),
                ('Approaches', models.BooleanField(help_text='If the squirrel is seen approaching peoplel')),
                ('Indifferent', models.BooleanField(help_text='If the squirrel is indifferent to human presence')),
                ('Runs_from', models.BooleanField(help_text='If the squirrel is running from human')),
                ('Tail_twitches', models.BooleanField(help_text='If the squirrel is seen twitching its tail')),
                ('Other_activities', models.BooleanField(help_text='If there is any other types of interactions between squirrels and humans')),
            ],
        ),
    ]
