# Generated by Django 3.2 on 2021-04-08 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('squirrel_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='squirrel_info',
            name='Age',
            field=models.CharField(blank=True, choices=[('adult', 'Adult'), ('juvenile', 'Juvenile')], help_text='Age, either Adult or Juvenile', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='squirrel_info',
            name='Approaches',
            field=models.BooleanField(blank=True, help_text='If the squirrel is seen approaching peoplel', null=True),
        ),
        migrations.AlterField(
            model_name='squirrel_info',
            name='Chasing',
            field=models.BooleanField(blank=True, help_text='If the squirrel is seen chasing', null=True),
        ),
        migrations.AlterField(
            model_name='squirrel_info',
            name='Climbing',
            field=models.BooleanField(blank=True, help_text='If the squirrel is seen climbing', null=True),
        ),
        migrations.AlterField(
            model_name='squirrel_info',
            name='Color_notes',
            field=models.CharField(blank=True, help_text='commentary on the squirrel ', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='squirrel_info',
            name='Date',
            field=models.DateField(blank=True, help_text='Sighting session date', null=True),
        ),
        migrations.AlterField(
            model_name='squirrel_info',
            name='Eating',
            field=models.BooleanField(blank=True, help_text='If the squirrel is seen eating', null=True),
        ),
        migrations.AlterField(
            model_name='squirrel_info',
            name='Foraging',
            field=models.BooleanField(blank=True, help_text='If the squirrel is seen foraging', null=True),
        ),
        migrations.AlterField(
            model_name='squirrel_info',
            name='Hectare',
            field=models.CharField(blank=True, help_text='Hector grid ID', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='squirrel_info',
            name='Highlight_fur_color',
            field=models.CharField(blank=True, help_text='The highlight fur color of the squirrels', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='squirrel_info',
            name='Indifferent',
            field=models.BooleanField(blank=True, help_text='If the squirrel is indifferent to human presence', null=True),
        ),
        migrations.AlterField(
            model_name='squirrel_info',
            name='Kuks',
            field=models.BooleanField(blank=True, help_text='If the squirrel is heard kukking', null=True),
        ),
        migrations.AlterField(
            model_name='squirrel_info',
            name='Latitude',
            field=models.FloatField(blank=True, help_text='Squirrel latitude', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='squirrel_info',
            name='Location',
            field=models.CharField(blank=True, choices=[('above ground', 'Above Ground'), ('ground plane', 'Ground Plane')], help_text='location of the squirrel, either Ground Plane or Above Ground ', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='squirrel_info',
            name='Longtitude',
            field=models.FloatField(blank=True, help_text='Squirrel longtitude', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='squirrel_info',
            name='Moans',
            field=models.BooleanField(blank=True, help_text='If the squirrel is heard moaning', null=True),
        ),
        migrations.AlterField(
            model_name='squirrel_info',
            name='Other_activities',
            field=models.BooleanField(blank=True, help_text='If there is any other types of interactions between squirrels and humans', null=True),
        ),
        migrations.AlterField(
            model_name='squirrel_info',
            name='Primary_fur_color',
            field=models.CharField(blank=True, choices=[('gray', 'Gray'), ('cinnamon', 'Cinnamon'), ('black', 'Black')], help_text='The primary fur color of the squirrels', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='squirrel_info',
            name='Quaas',
            field=models.BooleanField(blank=True, help_text='If the squirrel is heard quaaing', null=True),
        ),
        migrations.AlterField(
            model_name='squirrel_info',
            name='Running',
            field=models.BooleanField(blank=True, help_text='If the squirrel is seen running', null=True),
        ),
        migrations.AlterField(
            model_name='squirrel_info',
            name='Runs_from',
            field=models.BooleanField(blank=True, help_text='If the squirrel is running from human', null=True),
        ),
        migrations.AlterField(
            model_name='squirrel_info',
            name='Shift',
            field=models.CharField(blank=True, choices=[('AM', 'AM'), ('PM', 'PM')], help_text='Whether the sighting session occurred in the morning or afternoon', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='squirrel_info',
            name='Specific_location',
            field=models.CharField(blank=True, help_text='specific location of the squirrel ', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='squirrel_info',
            name='Tail_flags',
            field=models.BooleanField(blank=True, help_text='If the squirrel is seen flagging its tail', null=True),
        ),
        migrations.AlterField(
            model_name='squirrel_info',
            name='Tail_twitches',
            field=models.BooleanField(blank=True, help_text='If the squirrel is seen twitching its tail', null=True),
        ),
        migrations.AlterField(
            model_name='squirrel_info',
            name='Unique_Squirrel_ID',
            field=models.CharField(blank=True, help_text='The unique ID of the squirrel', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='squirrel_info',
            name='combination_color',
            field=models.CharField(blank=True, help_text='permutations of primary and highlight colors observed', max_length=50, null=True),
        ),
    ]
