# Generated by Django 3.2 on 2021-04-09 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('squirrel_app', '0003_auto_20210408_2110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='squirrel_info',
            name='Hectare_squirrel_number',
            field=models.IntegerField(help_text='Number within the chronological sequence of squirrel sightings for a discrete sighting session', null=True),
        ),
    ]
