# Generated by Django 3.2 on 2021-04-11 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('squirrel_app', '0004_alter_squirrel_info_hectare_squirrel_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='squirrel_info',
            name='Location',
            field=models.CharField(blank=True, help_text='Location of the squirrel, either Ground Plane or Above Ground ', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='squirrel_info',
            name='Specific_location',
            field=models.CharField(blank=True, help_text='Specific location of the squirrel ', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='squirrel_info',
            name='combination_color',
            field=models.CharField(blank=True, help_text='Permutations of primary and highlight colors observed', max_length=50, null=True),
        ),
    ]
