# Generated by Django 3.2 on 2021-04-11 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('squirrel_app', '0006_auto_20210411_0238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='squirrel_info',
            name='Longtitude',
            field=models.FloatField(blank=True, help_text='Squirrel longtitude\n', max_length=50, null=True),
        ),
    ]
