# Generated by Django 3.2 on 2021-04-11 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('squirrel_app', '0007_alter_squirrel_info_longtitude'),
    ]

    operations = [
        migrations.AlterField(
            model_name='squirrel_info',
            name='Longtitude',
            field=models.FloatField(blank=True, help_text='Squirrel longtitude', max_length=50, null=True),
        ),
    ]
