# Generated by Django 3.2 on 2021-04-14 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('squirrel_app', '0008_alter_squirrel_info_longtitude'),
    ]

    operations = [
        migrations.AlterField(
            model_name='squirrel_info',
            name='Age',
            field=models.CharField(blank=True, choices=[('Adult', 'Adult'), ('Juvenile', 'Juvenile')], help_text='Age, either Adult or Juvenile', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='squirrel_info',
            name='Color_notes',
            field=models.CharField(blank=True, help_text='commentary on the squirrel ', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='squirrel_info',
            name='Date',
            field=models.CharField(blank=True, help_text='Sighting session date', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='squirrel_info',
            name='Hectare',
            field=models.CharField(blank=True, help_text='Hector grid ID', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='squirrel_info',
            name='Highlight_fur_color',
            field=models.CharField(blank=True, help_text='The highlight fur color of the squirrels', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='squirrel_info',
            name='Location',
            field=models.CharField(blank=True, help_text='Location of the squirrel, either Ground Plane or Above Ground ', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='squirrel_info',
            name='Other_activities',
            field=models.CharField(blank=True, help_text='If there is any other types of interactions between squirrels and humans', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='squirrel_info',
            name='Primary_fur_color',
            field=models.CharField(blank=True, choices=[('Gray', 'Gray'), ('Cinnamon', 'Cinnamon'), ('Black', 'Black')], help_text='The primary fur color of the squirrels', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='squirrel_info',
            name='Shift',
            field=models.CharField(blank=True, choices=[('AM', 'AM'), ('PM', 'PM')], help_text='Whether the sighting session occurred in the morning or afternoon', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='squirrel_info',
            name='Specific_location',
            field=models.CharField(blank=True, help_text='Specific location of the squirrel ', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='squirrel_info',
            name='Unique_Squirrel_ID',
            field=models.CharField(blank=True, help_text='The unique ID of the squirrel', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='squirrel_info',
            name='combination_color',
            field=models.CharField(blank=True, help_text='Permutations of primary and highlight colors observed', max_length=500, null=True),
        ),
    ]
